Added object highlighting and minor fixes
ease-crc/openease pull request #82
Opened 2021-02-23 16:29 UTC by sasjonge

Added object highlighting and minor fixes to event participation graph.

2021-02-23 16:32 UTC, sasjonge commented
Depends on this PR:
https://github.com/ease-crc/openease_threejs/pull/2

2021-02-24 09:39 UTC, daniel86 requested changes

2021-02-24 09:39 UTC, daniel86 commented on knowrob/rules/src/data_vis/canvas.pl
> +	maplist(has_base_link_name, Objs, Links),
this will not work for e.g. facings in REFILLS.
I sent you a mapper function you can use via Jabber, remember?
Please use the one I sent to you

2021-02-25 13:57 UTC, daniel86 approved these changes

2021-02-25 13:58 UTC, merged